// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v7.34.1
// source: combos.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { BehaviorBinding } from "./keymap";

export const protobufPackage = "zmk.combos";

export enum AddComboErrorCode {
  ADD_COMBO_ERR_OK = 0,
  ADD_COMBO_ERR_GENERIC = 1,
  ADD_COMBO_ERR_NO_SPACE = 2,
  ADD_COMBO_ERR_INVALID_PARAMETERS = 3,
  UNRECOGNIZED = -1,
}

export function addComboErrorCodeFromJSON(object: any): AddComboErrorCode {
  switch (object) {
    case 0:
    case "ADD_COMBO_ERR_OK":
      return AddComboErrorCode.ADD_COMBO_ERR_OK;
    case 1:
    case "ADD_COMBO_ERR_GENERIC":
      return AddComboErrorCode.ADD_COMBO_ERR_GENERIC;
    case 2:
    case "ADD_COMBO_ERR_NO_SPACE":
      return AddComboErrorCode.ADD_COMBO_ERR_NO_SPACE;
    case 3:
    case "ADD_COMBO_ERR_INVALID_PARAMETERS":
      return AddComboErrorCode.ADD_COMBO_ERR_INVALID_PARAMETERS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AddComboErrorCode.UNRECOGNIZED;
  }
}

export function addComboErrorCodeToJSON(object: AddComboErrorCode): string {
  switch (object) {
    case AddComboErrorCode.ADD_COMBO_ERR_OK:
      return "ADD_COMBO_ERR_OK";
    case AddComboErrorCode.ADD_COMBO_ERR_GENERIC:
      return "ADD_COMBO_ERR_GENERIC";
    case AddComboErrorCode.ADD_COMBO_ERR_NO_SPACE:
      return "ADD_COMBO_ERR_NO_SPACE";
    case AddComboErrorCode.ADD_COMBO_ERR_INVALID_PARAMETERS:
      return "ADD_COMBO_ERR_INVALID_PARAMETERS";
    case AddComboErrorCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum RemoveComboErrorCode {
  REMOVE_COMBO_ERR_OK = 0,
  REMOVE_COMBO_ERR_GENERIC = 1,
  REMOVE_COMBO_ERR_INVALID_INDEX = 2,
  UNRECOGNIZED = -1,
}

export function removeComboErrorCodeFromJSON(object: any): RemoveComboErrorCode {
  switch (object) {
    case 0:
    case "REMOVE_COMBO_ERR_OK":
      return RemoveComboErrorCode.REMOVE_COMBO_ERR_OK;
    case 1:
    case "REMOVE_COMBO_ERR_GENERIC":
      return RemoveComboErrorCode.REMOVE_COMBO_ERR_GENERIC;
    case 2:
    case "REMOVE_COMBO_ERR_INVALID_INDEX":
      return RemoveComboErrorCode.REMOVE_COMBO_ERR_INVALID_INDEX;
    case -1:
    case "UNRECOGNIZED":
    default:
      return RemoveComboErrorCode.UNRECOGNIZED;
  }
}

export function removeComboErrorCodeToJSON(object: RemoveComboErrorCode): string {
  switch (object) {
    case RemoveComboErrorCode.REMOVE_COMBO_ERR_OK:
      return "REMOVE_COMBO_ERR_OK";
    case RemoveComboErrorCode.REMOVE_COMBO_ERR_GENERIC:
      return "REMOVE_COMBO_ERR_GENERIC";
    case RemoveComboErrorCode.REMOVE_COMBO_ERR_INVALID_INDEX:
      return "REMOVE_COMBO_ERR_INVALID_INDEX";
    case RemoveComboErrorCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum SetComboResponse {
  SET_COMBO_RESP_OK = 0,
  SET_COMBO_RESP_INVALID_LOCATION = 1,
  SET_COMBO_RESP_INVALID_BEHAVIOR = 2,
  SET_COMBO_RESP_INVALID_PARAMETERS = 3,
  UNRECOGNIZED = -1,
}

export function setComboResponseFromJSON(object: any): SetComboResponse {
  switch (object) {
    case 0:
    case "SET_COMBO_RESP_OK":
      return SetComboResponse.SET_COMBO_RESP_OK;
    case 1:
    case "SET_COMBO_RESP_INVALID_LOCATION":
      return SetComboResponse.SET_COMBO_RESP_INVALID_LOCATION;
    case 2:
    case "SET_COMBO_RESP_INVALID_BEHAVIOR":
      return SetComboResponse.SET_COMBO_RESP_INVALID_BEHAVIOR;
    case 3:
    case "SET_COMBO_RESP_INVALID_PARAMETERS":
      return SetComboResponse.SET_COMBO_RESP_INVALID_PARAMETERS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SetComboResponse.UNRECOGNIZED;
  }
}

export function setComboResponseToJSON(object: SetComboResponse): string {
  switch (object) {
    case SetComboResponse.SET_COMBO_RESP_OK:
      return "SET_COMBO_RESP_OK";
    case SetComboResponse.SET_COMBO_RESP_INVALID_LOCATION:
      return "SET_COMBO_RESP_INVALID_LOCATION";
    case SetComboResponse.SET_COMBO_RESP_INVALID_BEHAVIOR:
      return "SET_COMBO_RESP_INVALID_BEHAVIOR";
    case SetComboResponse.SET_COMBO_RESP_INVALID_PARAMETERS:
      return "SET_COMBO_RESP_INVALID_PARAMETERS";
    case SetComboResponse.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum SaveChangesErrorCode {
  SAVE_CHANGES_ERR_OK = 0,
  SAVE_CHANGES_ERR_GENERIC = 1,
  SAVE_CHANGES_ERR_NOT_SUPPORTED = 2,
  SAVE_CHANGES_ERR_NO_SPACE = 3,
  UNRECOGNIZED = -1,
}

export function saveChangesErrorCodeFromJSON(object: any): SaveChangesErrorCode {
  switch (object) {
    case 0:
    case "SAVE_CHANGES_ERR_OK":
      return SaveChangesErrorCode.SAVE_CHANGES_ERR_OK;
    case 1:
    case "SAVE_CHANGES_ERR_GENERIC":
      return SaveChangesErrorCode.SAVE_CHANGES_ERR_GENERIC;
    case 2:
    case "SAVE_CHANGES_ERR_NOT_SUPPORTED":
      return SaveChangesErrorCode.SAVE_CHANGES_ERR_NOT_SUPPORTED;
    case 3:
    case "SAVE_CHANGES_ERR_NO_SPACE":
      return SaveChangesErrorCode.SAVE_CHANGES_ERR_NO_SPACE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SaveChangesErrorCode.UNRECOGNIZED;
  }
}

export function saveChangesErrorCodeToJSON(object: SaveChangesErrorCode): string {
  switch (object) {
    case SaveChangesErrorCode.SAVE_CHANGES_ERR_OK:
      return "SAVE_CHANGES_ERR_OK";
    case SaveChangesErrorCode.SAVE_CHANGES_ERR_GENERIC:
      return "SAVE_CHANGES_ERR_GENERIC";
    case SaveChangesErrorCode.SAVE_CHANGES_ERR_NOT_SUPPORTED:
      return "SAVE_CHANGES_ERR_NOT_SUPPORTED";
    case SaveChangesErrorCode.SAVE_CHANGES_ERR_NO_SPACE:
      return "SAVE_CHANGES_ERR_NO_SPACE";
    case SaveChangesErrorCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Request {
  getCombos?: boolean | undefined;
  setCombo?: SetComboRequest | undefined;
  checkUnsavedChanges?: boolean | undefined;
  saveChanges?: boolean | undefined;
  discardChanges?: boolean | undefined;
  addCombo?: AddComboRequest | undefined;
  removeCombo?: RemoveComboRequest | undefined;
}

export interface Response {
  getCombos?: Combos | undefined;
  setCombo?: SetComboResponse | undefined;
  checkUnsavedChanges?: boolean | undefined;
  saveChanges?: SaveChangesResponse | undefined;
  discardChanges?: boolean | undefined;
  addCombo?: AddComboResponse | undefined;
  removeCombo?: RemoveComboResponse | undefined;
}

export interface Notification {
  unsavedChangesStatusChanged?: boolean | undefined;
}

/**
 * A single combo definition. Modeled on keymap's Layer/BehaviorBinding so the
 * frontend can reuse the existing behavior-display + behavior-picker machinery.
 */
export interface Combo {
  /**
   * key_positions is a nanopb static array (see combos.options.in) so it
   * round-trips through both the get_combos response encode AND the set_combo
   * request decode without per-field callbacks (the RPC framework decodes
   * requests generically with no callback setup).
   */
  keyPositions: number[];
  /** Bitmask of layers the combo is active on. 0 = all layers. */
  layers: number;
  binding:
    | BehaviorBinding
    | undefined;
  /**
   * sint32 (zigzag): timeout_ms and require_prior_idle_ms are commonly small or
   * -1 ("disabled"). Plain int32 encodes a negative as a 10-byte varint; sint32
   * encodes -1 as a single byte, shrinking set_combo/add_combo requests (and the
   * RX-buffer pressure flagged in A6 / the M2 RX-buffer fix). Transparent to the
   * firmware (still int32_t) and the TS client (still number).
   */
  timeoutMs: number;
  requirePriorIdleMs: number;
  slowRelease: boolean;
}

/**
 * Pairs a combo with its stable pool index (== virtual-key-position arg ==
 * NVS key). Indexes are not necessarily contiguous once add/delete land.
 */
export interface ComboEntry {
  index: number;
  combo: Combo | undefined;
}

export interface Combos {
  combos: ComboEntry[];
  maxCombos: number;
  maxKeysPerCombo: number;
}

/**
 * Edit the combo occupying pool slot `index` in place (M2: RAM-only, lost on
 * reboot). Mirrors keymap's SetLayerBindingRequest.
 */
export interface SetComboRequest {
  index: number;
  combo: Combo | undefined;
}

/**
 * Create a brand-new combo (M4). The firmware places it in the lowest free pool
 * slot and returns the assigned index. Mirrors keymap's AddLayerRequest, but
 * carries the full combo to create (unlike layers, a combo isn't useful empty).
 */
export interface AddComboRequest {
  combo: Combo | undefined;
}

export interface AddComboResponse {
  ok?: AddComboResponseDetails | undefined;
  err?: AddComboErrorCode | undefined;
}

export interface AddComboResponseDetails {
  index: number;
  combo: Combo | undefined;
}

/**
 * Delete the combo occupying pool slot `index` (M4). Mirrors keymap's
 * RemoveLayerRequest.
 */
export interface RemoveComboRequest {
  index: number;
}

export interface RemoveComboResponse {
  ok?: RemoveComboOk | undefined;
  err?: RemoveComboErrorCode | undefined;
}

export interface RemoveComboOk {
}

/**
 * Result of save_changes. Mirrors keymap's SaveChangesResponse so the frontend
 * can reuse the same error handling. NO_SPACE surfaces a full NVS partition.
 */
export interface SaveChangesResponse {
  ok?: boolean | undefined;
  err?: SaveChangesErrorCode | undefined;
}

function createBaseRequest(): Request {
  return {
    getCombos: undefined,
    setCombo: undefined,
    checkUnsavedChanges: undefined,
    saveChanges: undefined,
    discardChanges: undefined,
    addCombo: undefined,
    removeCombo: undefined,
  };
}

export const Request = {
  encode(message: Request, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.getCombos !== undefined) {
      writer.uint32(8).bool(message.getCombos);
    }
    if (message.setCombo !== undefined) {
      SetComboRequest.encode(message.setCombo, writer.uint32(18).fork()).ldelim();
    }
    if (message.checkUnsavedChanges !== undefined) {
      writer.uint32(24).bool(message.checkUnsavedChanges);
    }
    if (message.saveChanges !== undefined) {
      writer.uint32(32).bool(message.saveChanges);
    }
    if (message.discardChanges !== undefined) {
      writer.uint32(40).bool(message.discardChanges);
    }
    if (message.addCombo !== undefined) {
      AddComboRequest.encode(message.addCombo, writer.uint32(50).fork()).ldelim();
    }
    if (message.removeCombo !== undefined) {
      RemoveComboRequest.encode(message.removeCombo, writer.uint32(58).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Request {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.getCombos = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.setCombo = SetComboRequest.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.checkUnsavedChanges = reader.bool();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.saveChanges = reader.bool();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.discardChanges = reader.bool();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.addCombo = AddComboRequest.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.removeCombo = RemoveComboRequest.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Request {
    return {
      getCombos: isSet(object.getCombos) ? globalThis.Boolean(object.getCombos) : undefined,
      setCombo: isSet(object.setCombo) ? SetComboRequest.fromJSON(object.setCombo) : undefined,
      checkUnsavedChanges: isSet(object.checkUnsavedChanges)
        ? globalThis.Boolean(object.checkUnsavedChanges)
        : undefined,
      saveChanges: isSet(object.saveChanges) ? globalThis.Boolean(object.saveChanges) : undefined,
      discardChanges: isSet(object.discardChanges) ? globalThis.Boolean(object.discardChanges) : undefined,
      addCombo: isSet(object.addCombo) ? AddComboRequest.fromJSON(object.addCombo) : undefined,
      removeCombo: isSet(object.removeCombo) ? RemoveComboRequest.fromJSON(object.removeCombo) : undefined,
    };
  },

  toJSON(message: Request): unknown {
    const obj: any = {};
    if (message.getCombos !== undefined) {
      obj.getCombos = message.getCombos;
    }
    if (message.setCombo !== undefined) {
      obj.setCombo = SetComboRequest.toJSON(message.setCombo);
    }
    if (message.checkUnsavedChanges !== undefined) {
      obj.checkUnsavedChanges = message.checkUnsavedChanges;
    }
    if (message.saveChanges !== undefined) {
      obj.saveChanges = message.saveChanges;
    }
    if (message.discardChanges !== undefined) {
      obj.discardChanges = message.discardChanges;
    }
    if (message.addCombo !== undefined) {
      obj.addCombo = AddComboRequest.toJSON(message.addCombo);
    }
    if (message.removeCombo !== undefined) {
      obj.removeCombo = RemoveComboRequest.toJSON(message.removeCombo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Request>, I>>(base?: I): Request {
    return Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request>, I>>(object: I): Request {
    const message = createBaseRequest();
    message.getCombos = object.getCombos ?? undefined;
    message.setCombo = (object.setCombo !== undefined && object.setCombo !== null)
      ? SetComboRequest.fromPartial(object.setCombo)
      : undefined;
    message.checkUnsavedChanges = object.checkUnsavedChanges ?? undefined;
    message.saveChanges = object.saveChanges ?? undefined;
    message.discardChanges = object.discardChanges ?? undefined;
    message.addCombo = (object.addCombo !== undefined && object.addCombo !== null)
      ? AddComboRequest.fromPartial(object.addCombo)
      : undefined;
    message.removeCombo = (object.removeCombo !== undefined && object.removeCombo !== null)
      ? RemoveComboRequest.fromPartial(object.removeCombo)
      : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return {
    getCombos: undefined,
    setCombo: undefined,
    checkUnsavedChanges: undefined,
    saveChanges: undefined,
    discardChanges: undefined,
    addCombo: undefined,
    removeCombo: undefined,
  };
}

export const Response = {
  encode(message: Response, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.getCombos !== undefined) {
      Combos.encode(message.getCombos, writer.uint32(10).fork()).ldelim();
    }
    if (message.setCombo !== undefined) {
      writer.uint32(16).int32(message.setCombo);
    }
    if (message.checkUnsavedChanges !== undefined) {
      writer.uint32(24).bool(message.checkUnsavedChanges);
    }
    if (message.saveChanges !== undefined) {
      SaveChangesResponse.encode(message.saveChanges, writer.uint32(34).fork()).ldelim();
    }
    if (message.discardChanges !== undefined) {
      writer.uint32(40).bool(message.discardChanges);
    }
    if (message.addCombo !== undefined) {
      AddComboResponse.encode(message.addCombo, writer.uint32(50).fork()).ldelim();
    }
    if (message.removeCombo !== undefined) {
      RemoveComboResponse.encode(message.removeCombo, writer.uint32(58).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Response {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.getCombos = Combos.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.setCombo = reader.int32() as any;
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.checkUnsavedChanges = reader.bool();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.saveChanges = SaveChangesResponse.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.discardChanges = reader.bool();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.addCombo = AddComboResponse.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.removeCombo = RemoveComboResponse.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Response {
    return {
      getCombos: isSet(object.getCombos) ? Combos.fromJSON(object.getCombos) : undefined,
      setCombo: isSet(object.setCombo) ? setComboResponseFromJSON(object.setCombo) : undefined,
      checkUnsavedChanges: isSet(object.checkUnsavedChanges)
        ? globalThis.Boolean(object.checkUnsavedChanges)
        : undefined,
      saveChanges: isSet(object.saveChanges) ? SaveChangesResponse.fromJSON(object.saveChanges) : undefined,
      discardChanges: isSet(object.discardChanges) ? globalThis.Boolean(object.discardChanges) : undefined,
      addCombo: isSet(object.addCombo) ? AddComboResponse.fromJSON(object.addCombo) : undefined,
      removeCombo: isSet(object.removeCombo) ? RemoveComboResponse.fromJSON(object.removeCombo) : undefined,
    };
  },

  toJSON(message: Response): unknown {
    const obj: any = {};
    if (message.getCombos !== undefined) {
      obj.getCombos = Combos.toJSON(message.getCombos);
    }
    if (message.setCombo !== undefined) {
      obj.setCombo = setComboResponseToJSON(message.setCombo);
    }
    if (message.checkUnsavedChanges !== undefined) {
      obj.checkUnsavedChanges = message.checkUnsavedChanges;
    }
    if (message.saveChanges !== undefined) {
      obj.saveChanges = SaveChangesResponse.toJSON(message.saveChanges);
    }
    if (message.discardChanges !== undefined) {
      obj.discardChanges = message.discardChanges;
    }
    if (message.addCombo !== undefined) {
      obj.addCombo = AddComboResponse.toJSON(message.addCombo);
    }
    if (message.removeCombo !== undefined) {
      obj.removeCombo = RemoveComboResponse.toJSON(message.removeCombo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Response>, I>>(base?: I): Response {
    return Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Response>, I>>(object: I): Response {
    const message = createBaseResponse();
    message.getCombos = (object.getCombos !== undefined && object.getCombos !== null)
      ? Combos.fromPartial(object.getCombos)
      : undefined;
    message.setCombo = object.setCombo ?? undefined;
    message.checkUnsavedChanges = object.checkUnsavedChanges ?? undefined;
    message.saveChanges = (object.saveChanges !== undefined && object.saveChanges !== null)
      ? SaveChangesResponse.fromPartial(object.saveChanges)
      : undefined;
    message.discardChanges = object.discardChanges ?? undefined;
    message.addCombo = (object.addCombo !== undefined && object.addCombo !== null)
      ? AddComboResponse.fromPartial(object.addCombo)
      : undefined;
    message.removeCombo = (object.removeCombo !== undefined && object.removeCombo !== null)
      ? RemoveComboResponse.fromPartial(object.removeCombo)
      : undefined;
    return message;
  },
};

function createBaseNotification(): Notification {
  return { unsavedChangesStatusChanged: undefined };
}

export const Notification = {
  encode(message: Notification, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.unsavedChangesStatusChanged !== undefined) {
      writer.uint32(8).bool(message.unsavedChangesStatusChanged);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Notification {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.unsavedChangesStatusChanged = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Notification {
    return {
      unsavedChangesStatusChanged: isSet(object.unsavedChangesStatusChanged)
        ? globalThis.Boolean(object.unsavedChangesStatusChanged)
        : undefined,
    };
  },

  toJSON(message: Notification): unknown {
    const obj: any = {};
    if (message.unsavedChangesStatusChanged !== undefined) {
      obj.unsavedChangesStatusChanged = message.unsavedChangesStatusChanged;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Notification>, I>>(base?: I): Notification {
    return Notification.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Notification>, I>>(object: I): Notification {
    const message = createBaseNotification();
    message.unsavedChangesStatusChanged = object.unsavedChangesStatusChanged ?? undefined;
    return message;
  },
};

function createBaseCombo(): Combo {
  return { keyPositions: [], layers: 0, binding: undefined, timeoutMs: 0, requirePriorIdleMs: 0, slowRelease: false };
}

export const Combo = {
  encode(message: Combo, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    writer.uint32(10).fork();
    for (const v of message.keyPositions) {
      writer.int32(v);
    }
    writer.ldelim();
    if (message.layers !== 0) {
      writer.uint32(16).uint32(message.layers);
    }
    if (message.binding !== undefined) {
      BehaviorBinding.encode(message.binding, writer.uint32(26).fork()).ldelim();
    }
    if (message.timeoutMs !== 0) {
      writer.uint32(32).sint32(message.timeoutMs);
    }
    if (message.requirePriorIdleMs !== 0) {
      writer.uint32(40).sint32(message.requirePriorIdleMs);
    }
    if (message.slowRelease !== false) {
      writer.uint32(48).bool(message.slowRelease);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Combo {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCombo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag === 8) {
            message.keyPositions.push(reader.int32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.keyPositions.push(reader.int32());
            }

            continue;
          }

          break;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.layers = reader.uint32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.binding = BehaviorBinding.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.timeoutMs = reader.sint32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.requirePriorIdleMs = reader.sint32();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.slowRelease = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Combo {
    return {
      keyPositions: globalThis.Array.isArray(object?.keyPositions)
        ? object.keyPositions.map((e: any) => globalThis.Number(e))
        : [],
      layers: isSet(object.layers) ? globalThis.Number(object.layers) : 0,
      binding: isSet(object.binding) ? BehaviorBinding.fromJSON(object.binding) : undefined,
      timeoutMs: isSet(object.timeoutMs) ? globalThis.Number(object.timeoutMs) : 0,
      requirePriorIdleMs: isSet(object.requirePriorIdleMs) ? globalThis.Number(object.requirePriorIdleMs) : 0,
      slowRelease: isSet(object.slowRelease) ? globalThis.Boolean(object.slowRelease) : false,
    };
  },

  toJSON(message: Combo): unknown {
    const obj: any = {};
    if (message.keyPositions?.length) {
      obj.keyPositions = message.keyPositions.map((e) => Math.round(e));
    }
    if (message.layers !== 0) {
      obj.layers = Math.round(message.layers);
    }
    if (message.binding !== undefined) {
      obj.binding = BehaviorBinding.toJSON(message.binding);
    }
    if (message.timeoutMs !== 0) {
      obj.timeoutMs = Math.round(message.timeoutMs);
    }
    if (message.requirePriorIdleMs !== 0) {
      obj.requirePriorIdleMs = Math.round(message.requirePriorIdleMs);
    }
    if (message.slowRelease !== false) {
      obj.slowRelease = message.slowRelease;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Combo>, I>>(base?: I): Combo {
    return Combo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Combo>, I>>(object: I): Combo {
    const message = createBaseCombo();
    message.keyPositions = object.keyPositions?.map((e) => e) || [];
    message.layers = object.layers ?? 0;
    message.binding = (object.binding !== undefined && object.binding !== null)
      ? BehaviorBinding.fromPartial(object.binding)
      : undefined;
    message.timeoutMs = object.timeoutMs ?? 0;
    message.requirePriorIdleMs = object.requirePriorIdleMs ?? 0;
    message.slowRelease = object.slowRelease ?? false;
    return message;
  },
};

function createBaseComboEntry(): ComboEntry {
  return { index: 0, combo: undefined };
}

export const ComboEntry = {
  encode(message: ComboEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.index !== 0) {
      writer.uint32(8).uint32(message.index);
    }
    if (message.combo !== undefined) {
      Combo.encode(message.combo, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ComboEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseComboEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.index = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.combo = Combo.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ComboEntry {
    return {
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      combo: isSet(object.combo) ? Combo.fromJSON(object.combo) : undefined,
    };
  },

  toJSON(message: ComboEntry): unknown {
    const obj: any = {};
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    if (message.combo !== undefined) {
      obj.combo = Combo.toJSON(message.combo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ComboEntry>, I>>(base?: I): ComboEntry {
    return ComboEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ComboEntry>, I>>(object: I): ComboEntry {
    const message = createBaseComboEntry();
    message.index = object.index ?? 0;
    message.combo = (object.combo !== undefined && object.combo !== null) ? Combo.fromPartial(object.combo) : undefined;
    return message;
  },
};

function createBaseCombos(): Combos {
  return { combos: [], maxCombos: 0, maxKeysPerCombo: 0 };
}

export const Combos = {
  encode(message: Combos, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.combos) {
      ComboEntry.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    if (message.maxCombos !== 0) {
      writer.uint32(16).uint32(message.maxCombos);
    }
    if (message.maxKeysPerCombo !== 0) {
      writer.uint32(24).uint32(message.maxKeysPerCombo);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Combos {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCombos();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.combos.push(ComboEntry.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.maxCombos = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.maxKeysPerCombo = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Combos {
    return {
      combos: globalThis.Array.isArray(object?.combos) ? object.combos.map((e: any) => ComboEntry.fromJSON(e)) : [],
      maxCombos: isSet(object.maxCombos) ? globalThis.Number(object.maxCombos) : 0,
      maxKeysPerCombo: isSet(object.maxKeysPerCombo) ? globalThis.Number(object.maxKeysPerCombo) : 0,
    };
  },

  toJSON(message: Combos): unknown {
    const obj: any = {};
    if (message.combos?.length) {
      obj.combos = message.combos.map((e) => ComboEntry.toJSON(e));
    }
    if (message.maxCombos !== 0) {
      obj.maxCombos = Math.round(message.maxCombos);
    }
    if (message.maxKeysPerCombo !== 0) {
      obj.maxKeysPerCombo = Math.round(message.maxKeysPerCombo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Combos>, I>>(base?: I): Combos {
    return Combos.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Combos>, I>>(object: I): Combos {
    const message = createBaseCombos();
    message.combos = object.combos?.map((e) => ComboEntry.fromPartial(e)) || [];
    message.maxCombos = object.maxCombos ?? 0;
    message.maxKeysPerCombo = object.maxKeysPerCombo ?? 0;
    return message;
  },
};

function createBaseSetComboRequest(): SetComboRequest {
  return { index: 0, combo: undefined };
}

export const SetComboRequest = {
  encode(message: SetComboRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.index !== 0) {
      writer.uint32(8).uint32(message.index);
    }
    if (message.combo !== undefined) {
      Combo.encode(message.combo, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetComboRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetComboRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.index = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.combo = Combo.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetComboRequest {
    return {
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      combo: isSet(object.combo) ? Combo.fromJSON(object.combo) : undefined,
    };
  },

  toJSON(message: SetComboRequest): unknown {
    const obj: any = {};
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    if (message.combo !== undefined) {
      obj.combo = Combo.toJSON(message.combo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetComboRequest>, I>>(base?: I): SetComboRequest {
    return SetComboRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetComboRequest>, I>>(object: I): SetComboRequest {
    const message = createBaseSetComboRequest();
    message.index = object.index ?? 0;
    message.combo = (object.combo !== undefined && object.combo !== null) ? Combo.fromPartial(object.combo) : undefined;
    return message;
  },
};

function createBaseAddComboRequest(): AddComboRequest {
  return { combo: undefined };
}

export const AddComboRequest = {
  encode(message: AddComboRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.combo !== undefined) {
      Combo.encode(message.combo, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AddComboRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddComboRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.combo = Combo.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddComboRequest {
    return { combo: isSet(object.combo) ? Combo.fromJSON(object.combo) : undefined };
  },

  toJSON(message: AddComboRequest): unknown {
    const obj: any = {};
    if (message.combo !== undefined) {
      obj.combo = Combo.toJSON(message.combo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddComboRequest>, I>>(base?: I): AddComboRequest {
    return AddComboRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddComboRequest>, I>>(object: I): AddComboRequest {
    const message = createBaseAddComboRequest();
    message.combo = (object.combo !== undefined && object.combo !== null) ? Combo.fromPartial(object.combo) : undefined;
    return message;
  },
};

function createBaseAddComboResponse(): AddComboResponse {
  return { ok: undefined, err: undefined };
}

export const AddComboResponse = {
  encode(message: AddComboResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ok !== undefined) {
      AddComboResponseDetails.encode(message.ok, writer.uint32(10).fork()).ldelim();
    }
    if (message.err !== undefined) {
      writer.uint32(16).int32(message.err);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AddComboResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddComboResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ok = AddComboResponseDetails.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.err = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddComboResponse {
    return {
      ok: isSet(object.ok) ? AddComboResponseDetails.fromJSON(object.ok) : undefined,
      err: isSet(object.err) ? addComboErrorCodeFromJSON(object.err) : undefined,
    };
  },

  toJSON(message: AddComboResponse): unknown {
    const obj: any = {};
    if (message.ok !== undefined) {
      obj.ok = AddComboResponseDetails.toJSON(message.ok);
    }
    if (message.err !== undefined) {
      obj.err = addComboErrorCodeToJSON(message.err);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddComboResponse>, I>>(base?: I): AddComboResponse {
    return AddComboResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddComboResponse>, I>>(object: I): AddComboResponse {
    const message = createBaseAddComboResponse();
    message.ok = (object.ok !== undefined && object.ok !== null)
      ? AddComboResponseDetails.fromPartial(object.ok)
      : undefined;
    message.err = object.err ?? undefined;
    return message;
  },
};

function createBaseAddComboResponseDetails(): AddComboResponseDetails {
  return { index: 0, combo: undefined };
}

export const AddComboResponseDetails = {
  encode(message: AddComboResponseDetails, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.index !== 0) {
      writer.uint32(8).uint32(message.index);
    }
    if (message.combo !== undefined) {
      Combo.encode(message.combo, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AddComboResponseDetails {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddComboResponseDetails();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.index = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.combo = Combo.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddComboResponseDetails {
    return {
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      combo: isSet(object.combo) ? Combo.fromJSON(object.combo) : undefined,
    };
  },

  toJSON(message: AddComboResponseDetails): unknown {
    const obj: any = {};
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    if (message.combo !== undefined) {
      obj.combo = Combo.toJSON(message.combo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddComboResponseDetails>, I>>(base?: I): AddComboResponseDetails {
    return AddComboResponseDetails.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddComboResponseDetails>, I>>(object: I): AddComboResponseDetails {
    const message = createBaseAddComboResponseDetails();
    message.index = object.index ?? 0;
    message.combo = (object.combo !== undefined && object.combo !== null) ? Combo.fromPartial(object.combo) : undefined;
    return message;
  },
};

function createBaseRemoveComboRequest(): RemoveComboRequest {
  return { index: 0 };
}

export const RemoveComboRequest = {
  encode(message: RemoveComboRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.index !== 0) {
      writer.uint32(8).uint32(message.index);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RemoveComboRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveComboRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.index = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RemoveComboRequest {
    return { index: isSet(object.index) ? globalThis.Number(object.index) : 0 };
  },

  toJSON(message: RemoveComboRequest): unknown {
    const obj: any = {};
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RemoveComboRequest>, I>>(base?: I): RemoveComboRequest {
    return RemoveComboRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RemoveComboRequest>, I>>(object: I): RemoveComboRequest {
    const message = createBaseRemoveComboRequest();
    message.index = object.index ?? 0;
    return message;
  },
};

function createBaseRemoveComboResponse(): RemoveComboResponse {
  return { ok: undefined, err: undefined };
}

export const RemoveComboResponse = {
  encode(message: RemoveComboResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ok !== undefined) {
      RemoveComboOk.encode(message.ok, writer.uint32(10).fork()).ldelim();
    }
    if (message.err !== undefined) {
      writer.uint32(16).int32(message.err);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RemoveComboResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveComboResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ok = RemoveComboOk.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.err = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RemoveComboResponse {
    return {
      ok: isSet(object.ok) ? RemoveComboOk.fromJSON(object.ok) : undefined,
      err: isSet(object.err) ? removeComboErrorCodeFromJSON(object.err) : undefined,
    };
  },

  toJSON(message: RemoveComboResponse): unknown {
    const obj: any = {};
    if (message.ok !== undefined) {
      obj.ok = RemoveComboOk.toJSON(message.ok);
    }
    if (message.err !== undefined) {
      obj.err = removeComboErrorCodeToJSON(message.err);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RemoveComboResponse>, I>>(base?: I): RemoveComboResponse {
    return RemoveComboResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RemoveComboResponse>, I>>(object: I): RemoveComboResponse {
    const message = createBaseRemoveComboResponse();
    message.ok = (object.ok !== undefined && object.ok !== null) ? RemoveComboOk.fromPartial(object.ok) : undefined;
    message.err = object.err ?? undefined;
    return message;
  },
};

function createBaseRemoveComboOk(): RemoveComboOk {
  return {};
}

export const RemoveComboOk = {
  encode(_: RemoveComboOk, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RemoveComboOk {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveComboOk();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): RemoveComboOk {
    return {};
  },

  toJSON(_: RemoveComboOk): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<RemoveComboOk>, I>>(base?: I): RemoveComboOk {
    return RemoveComboOk.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RemoveComboOk>, I>>(_: I): RemoveComboOk {
    const message = createBaseRemoveComboOk();
    return message;
  },
};

function createBaseSaveChangesResponse(): SaveChangesResponse {
  return { ok: undefined, err: undefined };
}

export const SaveChangesResponse = {
  encode(message: SaveChangesResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ok !== undefined) {
      writer.uint32(8).bool(message.ok);
    }
    if (message.err !== undefined) {
      writer.uint32(16).int32(message.err);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SaveChangesResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSaveChangesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.ok = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.err = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SaveChangesResponse {
    return {
      ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : undefined,
      err: isSet(object.err) ? saveChangesErrorCodeFromJSON(object.err) : undefined,
    };
  },

  toJSON(message: SaveChangesResponse): unknown {
    const obj: any = {};
    if (message.ok !== undefined) {
      obj.ok = message.ok;
    }
    if (message.err !== undefined) {
      obj.err = saveChangesErrorCodeToJSON(message.err);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SaveChangesResponse>, I>>(base?: I): SaveChangesResponse {
    return SaveChangesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SaveChangesResponse>, I>>(object: I): SaveChangesResponse {
    const message = createBaseSaveChangesResponse();
    message.ok = object.ok ?? undefined;
    message.err = object.err ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
