// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v7.34.1
// source: combos.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

export const protobufPackage = "zmk.combos";

export interface Request {
  getCombos?: boolean | undefined;
}

export interface Response {
  getCombos?: Combos | undefined;
}

export interface Notification {
  unsavedChangesStatusChanged?: boolean | undefined;
}

/**
 * Milestone 0 walking-skeleton: empty container. Fleshed out in Milestone 1
 * with `repeated ComboEntry combos`, `max_combos`, `max_keys_per_combo`.
 */
export interface Combos {
}

function createBaseRequest(): Request {
  return { getCombos: undefined };
}

export const Request = {
  encode(message: Request, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.getCombos !== undefined) {
      writer.uint32(8).bool(message.getCombos);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Request {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.getCombos = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Request {
    return { getCombos: isSet(object.getCombos) ? globalThis.Boolean(object.getCombos) : undefined };
  },

  toJSON(message: Request): unknown {
    const obj: any = {};
    if (message.getCombos !== undefined) {
      obj.getCombos = message.getCombos;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Request>, I>>(base?: I): Request {
    return Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request>, I>>(object: I): Request {
    const message = createBaseRequest();
    message.getCombos = object.getCombos ?? undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return { getCombos: undefined };
}

export const Response = {
  encode(message: Response, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.getCombos !== undefined) {
      Combos.encode(message.getCombos, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Response {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.getCombos = Combos.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Response {
    return { getCombos: isSet(object.getCombos) ? Combos.fromJSON(object.getCombos) : undefined };
  },

  toJSON(message: Response): unknown {
    const obj: any = {};
    if (message.getCombos !== undefined) {
      obj.getCombos = Combos.toJSON(message.getCombos);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Response>, I>>(base?: I): Response {
    return Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Response>, I>>(object: I): Response {
    const message = createBaseResponse();
    message.getCombos = (object.getCombos !== undefined && object.getCombos !== null)
      ? Combos.fromPartial(object.getCombos)
      : undefined;
    return message;
  },
};

function createBaseNotification(): Notification {
  return { unsavedChangesStatusChanged: undefined };
}

export const Notification = {
  encode(message: Notification, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.unsavedChangesStatusChanged !== undefined) {
      writer.uint32(8).bool(message.unsavedChangesStatusChanged);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Notification {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.unsavedChangesStatusChanged = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Notification {
    return {
      unsavedChangesStatusChanged: isSet(object.unsavedChangesStatusChanged)
        ? globalThis.Boolean(object.unsavedChangesStatusChanged)
        : undefined,
    };
  },

  toJSON(message: Notification): unknown {
    const obj: any = {};
    if (message.unsavedChangesStatusChanged !== undefined) {
      obj.unsavedChangesStatusChanged = message.unsavedChangesStatusChanged;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Notification>, I>>(base?: I): Notification {
    return Notification.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Notification>, I>>(object: I): Notification {
    const message = createBaseNotification();
    message.unsavedChangesStatusChanged = object.unsavedChangesStatusChanged ?? undefined;
    return message;
  },
};

function createBaseCombos(): Combos {
  return {};
}

export const Combos = {
  encode(_: Combos, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Combos {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCombos();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Combos {
    return {};
  },

  toJSON(_: Combos): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Combos>, I>>(base?: I): Combos {
    return Combos.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Combos>, I>>(_: I): Combos {
    const message = createBaseCombos();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
